name: senseflow
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.0
  file_picker: ^6.1.1
  google_fonts: ^5.0.0
  table_calendar: ^3.0.9
  path: ^1.9.0
  path_provider: ^2.1.2
  pdf: ^3.10.1
  printing: ^5.13.3
  csv: ^5.0.2
  excel: ^2.0.4
  file_saver: ^0.2.9
  open_filex: ^4.3.4
  # для проверки, что мы в web (для сохранения Excel через <a>)
  flutter_web_plugins:
    sdk: flutter
  math_expressions: ^3.0.0

dependency_overrides:
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
      ref: master

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Roboto.ttf
